version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8000"
      - "443:8001"
    volumes:
      - /etc/letsencrypt:/etc/nginx/letsencrypt
      - ./raffle:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -w 4 raffle.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - ./raffle:/src
    expose:
      - "8000"
